### ISSUE TITLE
Duplicate middleware name NewRelicDynamoDocClientMiddleware

### ISSUE THREAD

**Issue by suryajak** [newrelic/node-newrelic-aws-sdk#144]
This layer is breaking our lambda using NodeJS14x runtime and deployed in  us-west-2. :

```
"errorMessage": "Duplicate middleware name 'NewRelicDynamoDocClientMiddleware'",
  "trace": [
    "CustomError: Duplicate middleware name 'NewRelicDynamoDocClientMiddleware'",
    "    at /var/task/src/app.js:1:42462",
    "    at U (/var/task/src/app.js:1:42477)",
    "    at Y (/var/task/src/app.js:1:42568)",
    "    at Runtime.V (/var/task/src/app.js:1:43593)",
    "    at /opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1313:22",
    "    at LegacyContextManager.runInContext (/opt/nodejs/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)",
    "    at TransactionShim.applySegment (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1303:25)",
    "    at Runtime.wrappedHandler (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:186:20)",
    "    at /opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1313:22",
    "    at LegacyContextManager.runInContext (/opt/nodejs/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)"
    
```

This is the relevant yml config:

```
 newRelic:
    accountId: ${env:NR_ACCOUNTID}
    apiKey: ${env:NR_LICENSE_KEY}
    enableExtensionLogs: false 
    enableIntegration: true     
```

What am I missing?
